# Generated by Django 2.0 on 2018-03-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdc_number', models.IntegerField(max_length=128)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(default='', max_length=128)),
                ('respuesta', models.CharField(default='', max_length=128)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancoCliente.Cuentas')),
            ],
        ),
    ]
