# Generated by Django 2.0.3 on 2018-04-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoCliente', '0002_auto_20180326_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='ci',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='fecha_vencimiento',
            field=models.CharField(default='', max_length=152),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='secret_number',
            field=models.CharField(default='', max_length=152),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='tdc_number',
            field=models.CharField(max_length=152, unique=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.CharField(default='', max_length=152),
        ),
    ]
