# Generated by Django 2.0 on 2018-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoCliente', '0003_auto_20180327_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='fecha_vencimiento',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='secret_number',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='tdc_number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
