# Generated by Django 2.0 on 2018-03-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoCliente', '0004_auto_20180327_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='ci',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='fecha_vencimiento',
            field=models.CharField(default='', max_length=152),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='secret_number',
            field=models.CharField(default='', max_length=152),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='tdc_number',
            field=models.CharField(max_length=152, unique=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.CharField(default='', max_length=152),
        ),
    ]
