# Generated by Django 2.0.3 on 2018-04-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancoCliente', '0003_auto_20180409_0008'),
        ('bancoCliente', '0005_auto_20180327_2054'),
    ]

    operations = [
    ]
